service: auth-service-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    JWT_SECRET: ${env:JWT_SECRET}

plugins:
  - serverless-offline


functions:
  authenticate:
    name: authenticate-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true
